M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu24.04.1} date 2024-07-06T11:56:44-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-06T11:56:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X25.13Y-27.11
X25.13Y-32.89
M30
